name: Code checks

on:
  pull_request:
    branches:
      - main  # run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Miniconda
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: conda/general.txt
          activate-environment: CODS26
          use-mamba: true

      # Run tests
      - run: pytest tests/
      - run: flake8 src/
      - run: mypy src/
